name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd danishamin-portfolio || git clone https://github.com/geoxpyder/danishamin-portfolio.git && cd danishamin-portfolio
            git pull origin main

            docker build -t portfolio .

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d -p 80:80 --name portfolio portfolio